IMAGE_NAME = owncloud
IMAGE_VERSION = latest
IMAGE_VERSION_ALIASES =	8.0.4 8.0 8
IMAGE_TITLE = ownCloud
IMAGE_DESCRIPTION = ownCloud
IMAGE_DOC_URL = https://www.scaleway.com/docs/deploy-owncloud-with-object-storage
IMAGE_SOURCE_URL = https://github.com/scaleway-community/scaleway-owncloud
IMAGE_VENDOR_URL = https://owncloud.org
IMAGE_BOOTSCRIPT = mainline 4.9
