#!/bin/bash

check_mysql()
{
  mysqladmin ping
}

USER_PASSWORD=$(head /dev/urandom -c 512 | sha1sum | awk '// { print $1; }')
PUBLIC_IP=$(scw-metadata --cached PUBLIC_IP_ADDRESS)

# Give access to webserver
chown -R www-data:www-data /var/www/html/owncloud/apps/
chown -R www-data:www-data /var/www/html/owncloud/config/
chown -R www-data:www-data /var/www/html/owncloud/themes/
chown -R www-data:www-data /var/www/html/owncloud/data/
chown -R root:www-data /var/lib/php/
chown root:www-data /var/www/html/owncloud/.htaccess

while !(check_mysql)
do
  sleep 3
done

mysql -e "CREATE DATABASE owncloud_db;
          CREATE USER 'owncloud'@'localhost' IDENTIFIED BY '${USER_PASSWORD}';
          GRANT ALL PRIVILEGES ON owncloud_db.* TO 'owncloud'@'localhost';
          FLUSH PRIVILEGES;"

# Add infos for user
sed -i "s/<database-passwd>/$USER_PASSWORD/" /usr/share/doc/scaleway/owncloud/README
sed -i "s/<your-ip>/$PUBLIC_IP/" /usr/share/doc/scaleway/owncloud/README

# Disable the service that ran this script, only need it once
systemctl disable init-owncloud
