#!/bin/sh

DEBIAN_FRONTEND="noninteractive"

URL=$(/usr/local/bin/oc-metadata --cached VOLUMES_0_SERVER_ID).pub.cloud.scaleway.com

pip install --upgrade pyopenssl ndg-httpsclient pyasn1
git clone -b 'v0.4.0' https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
/opt/letsencrypt/letsencrypt-auto --apache -d $URL --register-unsafely-without-email --agree-tos

update-rc.d letsencrypt disable -f || true
update-rc.d letsencrypt remove -f || true
crontab -l | { cat; echo "30 2 * * 1 /usr/local/sbin/le-renew $URL >> /var/log/le-renew.log"; } | crontab -
rm -fr /etc/init.d/letsencrypt || true
